# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Setlist
  description: setlist
  icon: 'title'
  tags: ['setlist']

# Defines the structure of this component, as well as the default values
blueprint:
  title: ''
  text: ''
  button_text: ''
  setlist: ''
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
