# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Gallery
  description: Gallery
  icon: 'gallery'
  tags: ['gallery']

# Defines the structure of this component, as well as the default values
blueprint:
  images:
    - image: ''
      image_mobile: ''
      title: ''
  anchor: ''
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
