# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Hero
  description: Hero
  icon: 'image'
  tags: ['hero']

# Defines the structure of this component, as well as the default values
blueprint:
  background_image: ''
  background_image_mobile: ''
  background_alt: ''
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
