# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Heading
  description: Heading section
  icon: "title"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: ""
  tag: h2


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
