# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Introduction
  description: Introduction
  icon: 'title'
  tags: ['introduction']

# Defines the structure of this component, as well as the default values
blueprint:
  title: ''
  text: ''
  members:
    - name: ''
      image: ''
      instrument: ''
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
