# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Counter
  description: Counter
  icon: 'numbers'
  tags: ['counter']

# Defines the structure of this component, as well as the default values
blueprint:
  items:
    - number: ''
      text: ''
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
