# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Button
  description: Button section
  icon: "ads_click"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text: ""
  link: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
