# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Home Hero Carousel
  description: Home Hero Carousel
  icon: 'cottage'
  tags: ['hero', 'carousel']

# Defines the structure of this component, as well as the default values
blueprint:
  background_image: ''
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
