# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Wysiwyg
  description: wysiwyg
  icon: 'text'
  tags: ['wysiwyg']

# Defines the structure of this component, as well as the default values
blueprint:
  text: ''
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
