# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Dates
  description: Dates
  icon: 'calendar'
  tags: ['dates']

# Defines the structure of this component, as well as the default values
blueprint:
  title: ''
  text: ''
  icon: ''
  dates:
    - title: ''
      date: ''
      location: ''
      is_bohemian: false
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
