# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Contact
  description: Contact
  icon: 'contact'
  tags: ['contact']

# Defines the structure of this component, as well as the default values
blueprint:
  title: ''
  text: ''
  contact_id: ''
  anchor: ''
  success_message: ''
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
